image: python:3.7-stretch

stages:
  - package

.install_tools: &install_tools |
  export DEBIAN_FRONTEND=noninteractive
  apt update
  apt -y install wget
  wget "$OPSIDEVTOOLS_URL_LINUX_X64" -O opsi-dev-tools.tar.gz
  tar -xvf opsi-dev-tools.tar.gz

package:obs_int:
  stage: package
  script:
    - *install_tools
    - ./opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:development

package:obs_ext:
  stage: package
  script:
    - *install_tools
    - ./opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:development
  only:
    - /^release/.*$/i
    - tags
    - web
